### PR TITLE
Update code

### PR DESCRIPTION
**Pull request by Sanduhr32**
I taught you how to play the flute, play the flute.

### CODE REVIEW

**Comment by lordjbs** [comment]
Hey, I will look into it, still, I won't change the file stuff to java things, cause I personally like commons.
Also, the java file read you made is broken, Soo xD

**Comment by Sanduhr32** [comment]
Np i saw it because in my third check sorry. i was hotfixing it before you comment :P

**Comment by Sanduhr32** [comment]
Btw stfu travis ci i'm not the guy who fixes src/test

**Comment by Sanduhr32** [comment]
call me dumb pressed wrong button

**Comment by lordjbs** [comment]
ok ur dumb

**Comment by lordjbs** [comment]
xD

**Comment by lordjbs** [comment]
Some stuff i liked got added, thanks.

**Pull request closed without merging**
